<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks Condition="'$(LibraryFrameworks)'==''">net461;netstandard2.1;net6.0;net8.0;net10.0</TargetFrameworks>
		<TargetFrameworks Condition="'$(LibraryFrameworks)'!=''">$(LibraryFrameworks)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Inkslab\Inkslab.csproj" />
	</ItemGroup>
	
</Project>
